name: Deploy Component Library
on:
  push:
    branches:
      - 'main'
jobs:
  component-library-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Deploy storybook
        run: npm run storybook:deploy --  --source-branch main --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
